### PR TITLE
Prepare covidcast 0.4.3 release for CRAN

### PR DESCRIPTION
**Pull request by capnrefsmmat**
This branch contains a variety of changes I made while preparing for CRAN release. I will solicit some testers and then prepare to submit to CRAN.

### CODE REVIEW

**Comment by dshemetov** [comment]
FWIW just ran `devtools::check()` on this package. Everything looks good locally 👍, except for the ghost-differences (no actual visible differences) in the plot SVG outputs 👻.

**Comment by dshemetov** [comment]
Did we want to include #590 in this release?

**Comment by capnrefsmmat** [comment]
Yes, I think so, so I'll merge that and rebase.

**Comment by capnrefsmmat** [comment]
Actually I will merge this (after having merged #590), then create a new PR for updating everything to make a release.

**Pull request merged**
