### PR TITLE
Have python module test on installed package

### PR DESCRIPTION
**Pull request by chinandrew**
In light of the packaging bug, changing unit tests to run on an intalled version of the package instead of directly on the code files. This is the same pattern as the indicator repo.

Summary of changes:
- Update makefile and documentation with relevant commands to install and test
- Remove some init files that aren't required
- Restructure the test directory just for organization (move files from tests/covidcast/* to just tests/)
- Rearrange some requirements now that the package dependencies are just installed through setup.py

### CODE REVIEW

**Comment by chinandrew** [comment]
for some reason tests are still passing even when i change to the buggy packaging path, so going to look into it some more.

**Comment by capnrefsmmat** [comment]
Did you verify that `pip install .`, without `-e`, only installs the files specified in `setup.py`?

**Comment by chinandrew** [comment]
> Did you verify that `pip install .`, without `-e`, only installs the files specified in `setup.py`?

I checked that without -e, the improper `package_data` specifications in setup.py lead to the expected errors when running the installed package

**Comment by chinandrew** [comment]
Here's the installed folder, looks like it grabbed all the right files.:

```
andrew@andrew-ThinkPad-X230:~/Documents/covidcast/Python-packages/covidcast-py$ tree env/lib/python3.8/site-packages/covidcast/
env/lib/python3.8/site-packages/covidcast/
├── covidcast.py
├── errors.py
├── geography.py
├── geo_mappings
│   ├── county_census.csv
│   ├── msa_census.csv
│   └── state_census.csv
├── __init__.py
├── plotting.py
├── __pycache__
│   ├── covidcast.cpython-38.pyc
│   ├── errors.cpython-38.pyc
│   ├── geography.cpython-38.pyc
│   ├── __init__.cpython-38.pyc
│   └── plotting.cpython-38.pyc
└── shapefiles
    ├── county
    │   ├── cb_2019_us_county_5m.cpg
    │   ├── cb_2019_us_county_5m.dbf
    │   ├── cb_2019_us_county_5m.prj
    │   ├── cb_2019_us_county_5m.shp
    │   ├── cb_2019_us_county_5m.shp.ea.iso.xml
    │   ├── cb_2019_us_county_5m.shp.iso.xml
    │   └── cb_2019_us_county_5m.shx
    ├── hrr
    │   ├── geo_export_ad86cff5-e5ed-432e-9ec2-2ce8732099ee.dbf
    │   ├── geo_export_ad86cff5-e5ed-432e-9ec2-2ce8732099ee.prj
    │   ├── geo_export_ad86cff5-e5ed-432e-9ec2-2ce8732099ee.shp
    │   └── geo_export_ad86cff5-e5ed-432e-9ec2-2ce8732099ee.shx
    ├── msa
    │   ├── cb_2019_us_cbsa_5m.cpg
    │   ├── cb_2019_us_cbsa_5m.dbf
    │   ├── cb_2019_us_cbsa_5m.prj
    │   ├── cb_2019_us_cbsa_5m.shp
    │   ├── cb_2019_us_cbsa_5m.shp.ea.iso.xml
    │   ├── cb_2019_us_cbsa_5m.shp.iso.xml
    │   └── cb_2019_us_cbsa_5m.shx
    └── state
        ├── cb_2019_us_state_5m.cpg
        ├── cb_2019_us_state_5m.dbf
        ├── cb_2019_us_state_5m.prj
        ├── cb_2019_us_state_5m.shp
        ├── cb_2019_us_state_5m.shp.ea.iso.xml
        ├── cb_2019_us_state_5m.shp.iso.xml
        └── cb_2019_us_state_5m.shx

7 directories, 38 files
```

**Review by capnrefsmmat — APPROVED** [review]

**Pull request merged**
