### PR TITLE
Really prepare covidcast 0.4.3 for release

### PR DESCRIPTION
**Pull request by capnrefsmmat**
Update to #571 to finalize a few details.

I think this is basically ready to go to CRAN, except perhaps for the flaky plot tests; we may need to guard those with an R version check again, like we did before b16ededb64c removed those checks from `test-plot.R`. We'll see if it passes on CI now, and whether the tests will pass on CRAN.

### CODE REVIEW

**Review by dshemetov — CHANGES_REQUESTED** [review]
Updates look fine, but still getting some CI errors

```r
  Error: 'eval_forecasts' is not an exported object from 'namespace:scoringutils'
  Backtrace:
      ▆
   1. └─scoringutils::eval_forecasts at test-err-measures.R:128:2
   2.   └─base::getExportedValue(pkg, name)
  ── Error (test-err-measures.R:172:3): wis over/under works, 2 intervals and median ──
  Error: 'eval_forecasts' is not an exported object from 'namespace:scoringutils'
  Backtrace:
      ▆
   1. └─scoringutils::eval_forecasts at test-err-measures.R:172:2
   2.   └─base::getExportedValue(pkg, name)
  
  [ FAIL 2 | WARN 0 | SKIP 3 | PASS 214 ]
```

These are tests in evalcast failing because [`scoringutils` replaced `eval_forecasts` with `score`. in 1.0.0](https://github.com/epiforecasts/scoringutils/releases/tag/v1.0.0). These were fixed in the [evalcast branch](https://github.com/cmu-delphi/covidcast/blob/evalcast/R-packages/evalcast/tests/testthat/test-err-measures.R#L132-L133). Should we cherry-pick that commit (probably not because [it's in a commit that touches more than the tests](https://github.com/cmu-delphi/covidcast/commit/c9ebbeab421891c838771704ffa9d3ee13213980#diff-a10167006de2100654096f6ee1d777b0f0af72edfc5cf8d745357359d7b34692)) or sync this branch with `evalcast`? 
- the second option will make confusing diffs with `main`; we could merge `evalcast` into `main` before to reduce that, but I don't know the implications of merging into the main branch for this repo; how many users using `main` use `evalcast`? I would hope zero?
- the first option will still be confusing because of the commit touching many files

**Comment by dshemetov** [comment]
There's also a failing test in the Python client file

```py
        # test w/ megacounty combine
        mega = plotting._join_county_geo_df(test_input, "county_code", geo_info, "left", True)
        expected_mega = gpd.read_file(
            os.path.join(CURRENT_PATH,
                         "reference_data/expected__join_county_geo_df_mega.gpkg"),
            dtype={"geo_value": str})
>       pd.testing.assert_frame_equal(expected_mega, mega)

E   AssertionError: ExtensionArray are different
E   
E   ExtensionArray values are different (33.33333 %)
E   [index]: [0, 1, 2]
E   [left]:  [POLYGON ((-76.71131299999999 39.371933, -76.626193 39.37201 ...
E   [right]: [POLYGON ((-76.71131299999999 39.371933, -76.626193 39.372017 ,...
```

Trying to figure out what this is about.

**Comment by dshemetov** [comment]
There appears to be some small differences in the coordinates in the megacounty MultiPolygon:

```
(Pdb) mega
  county_code  test_value  test_value2 state_fips                                           geometry
0       24510         1.5         21.5         24  POLYGON ((-76.71131 39.37193, -76.62619 39.372...
1       31169         2.5         32.5         31  POLYGON ((-97.82082 40.35054, -97.36869 40.350...
2       37000         3.0         34.0         37  MULTIPOLYGON (((-83.93643 34.98748, -83.93665 ...

(Pdb) expected_mega
  county_code  test_value  test_value2 state_fips                                           geometry
0       24510         1.5         21.5         24  POLYGON ((-76.71131 39.37193, -76.62619 39.372...
1       31169         2.5         32.5         31  POLYGON ((-97.82082 40.35054, -97.36869 40.350...
2       37000         3.0         34.0         37  MULTIPOLYGON (((-77.71592 34.29272, -77.74014 ...
```

Row 2 is where the issues are (you can even see it in the first coordinate there. I'm not familiar with this codebase enough to say what is going wrong.

**Comment by capnrefsmmat** [comment]
I didn't change anything in evalcast or the Python client in this PR, so those failures are unrelated. For the Python client, maybe one of the packages it uses changed how it rounds or processes geographic coordinates?

For evalcast, @nmdefries do you know why the evalcast CI is persistently failing on the main branch?

**Comment by dshemetov** [comment]
Like I mentioned above, [this hasn't been fixed](https://github.com/cmu-delphi/covidcast/blob/main/R-packages/evalcast/tests/testthat/test-err-measures.R#L128-L130) on `main`. `scoringutils::eval_forecasts` is now `scoringutils::score`.

**Comment by dshemetov** [comment]
I'm trying different pairings of `geopandas` and `shapely` versions, dated around the time that you and Andrew were working on the Python package and I'm still getting the error.

**Comment by capnrefsmmat** [comment]
Yeah, that's pretty weird. The Python package was last touched nearly a year ago, and CI passed back then, so something has changed in the mean time. I'm not sure if that should block this release, though, since we're not releasing a new Python client now. Definitely worth making an issue so we investigate it, though.

As for evalcast: why hasn't evalcast merged into main in a long time? Was that just because developing on a branch is convenient, or is there some use case for keeping the evalcast on the main branch fixed at some specific version?

**Comment by nmdefries** [comment]
> As for evalcast: why hasn't evalcast merged into main in a long time? Was that just because developing on a branch is convenient, or is there some use case for keeping the evalcast on the main branch fixed at some specific version?

Maybe @dajmcdon knows for sure. My impression was that the changes in `evalcast` to support the forecast evaluation pipeline are considered auxiliary and weren't intended to be on `main`.

**Comment by dshemetov** [comment]
For me, it was mostly a Chesterton's Fence deal: I had only worked with the evalcast package, saw that the evalcast branch was far ahead, and figured there was a reason that main was behind.

**Comment by dshemetov** [comment]
I'm ok with filing the failing Python CI issue elsewhere, especially given that we're moving towards `epidatpy`.

**Comment by capnrefsmmat** [comment]
Successfully released to CRAN following testing in the forecast pipeline and a couple minor changes to meet CRAN rules. Let's hope it works!

**Pull request merged**
