### PR TITLE
Update covidcast description

### PR DESCRIPTION
**Pull request by ryantibs**
Hi all, particularly @capnrefsmmat, this is just a trivial update to the covidcast DESCRIPTION file. I added Sarah as an author (my understanding is that she recently implemented choropleth maps for MSAs and HRRs?), and made the indentation everywhere 4 spaces, as [per the instructions here](https://r-pkgs.org/description.html).

Alex, is there anyone else to add as an author (or a contributor)? If so you can sneak it in another commit here on this branch.

### CODE REVIEW

**Comment by capnrefsmmat** [comment]
Requesting review from @sarah-colq to ensure she's credited the way she'd prefer.

Also, please see #284 or `DEVELOP.md`: we're going to branch from `r-pkg-devel` rather than `main`, so we can merge into a development branch and test features before releasing them publicly. I'll probably just cherry-pick this commit, since if I switch the base branch it wants to bring in a bunch of other stuff from `main.`

**Review by sgsmob — APPROVED** [review]
Other than the branch workflow issues described in the comment above, this is good.

**Review by sarah-colq — APPROVED** [review]

**Comment by sarah-colq** [comment]
Sorry didn't see this before!

**Comment by capnrefsmmat** [comment]
Thanks. I'll make a new PR to add this on the `r-pkg-devel` branch.

**Pull request closed without merging**
