### PR TITLE
bug(evalcast): remove title from labs in plots

### LINKED ISSUE #640: plot_calibration gives .data errors, based on type of plot, when following evalcast tutorial
I am trying to replicate the tutorial found at https://cmu-delphi.github.io/covidcast/evalcastR/articles/evalcast.html on my local machine. Things generally work (thanks Dmitry!) up until `plot_calibration`.

The first instance of `plot_calibration` is giving this issue, which occurs in `format_wedgeplot`, but refers to subsetting .data outside of a data mask context.
image

The second instance gives an identical issue and traceback to the first.

The third instance gives a similar subsetting .data issue, but says it occurs in `format_traditional_calib_plot`.
image

Are there packages on my end that I am missing and need to install/update?

### PR DESCRIPTION
**Pull request by dshemetov**
closes #640 

- removes `title` argument from the labs
- also updates the DESCRIPTION file with remotes that work with devtools, remotes, and pak

### CODE REVIEW

**Comment by brookslogan** [comment]
Thanks; do you know what the plot labels look like now in the vignette?

**Comment by dshemetov** [comment]
They looked unchanged to me 🤷, but I didn't look suuuper closely

**Review by brookslogan — APPROVED** [review]
Looks good!  This should fix vignette rendering and some user bugs.  We might want to revisit in another Issue if ~the guide labels are unclear or eating up a bunch of space now~ [we want a title].

**Comment by brookslogan** [comment]
If you look at the wedge plots [here](https://cmu-delphi.github.io/covidcast/evalcastR/articles/evalcast.html), for example, the text "Proportion below" and "Proportion above" labeling the colors should have changed.  It might be a better hack to just say "Proportion below" and "Proportion above" instead of the corresponding `sprintf` failures; I'm not sure what it's going to look like by default.

**Comment by brookslogan** [comment]
Sorry, neverymind, my bad. There shouldn't be a change; `sprintf` with `NULL` returns `character(0)`.

**Comment by dshemetov** [comment]
This is what the first plot looks like

image

**Comment by brookslogan** [comment]
Yep, it makes sense now; I thought `NULL` acted like `""` in `sprintf` but it actually acts like `character(0)`, so we're going from buggily saying "no title" ----> not saying anything about the title & getting no title.

**Comment by dshemetov** [comment]
Once CI finishes, I'll merge. I don't think we should continue adding features to this repo, so I wouldn't open a title issue.

**Comment by zterner-mitre** [comment]
Thanks for all your work on this!! I really appreciate it. I'd be happy to confirm that things work on my end once the changes are finished, just let me know how to proceed at that time if you can.

**Comment by dshemetov** [comment]
Thanks @zterner-mitre! Can you try running through the tutorial again after installing with

```r
pak::pkg_install("cmu-delphi/covidcast/R-packages/evalcast@ds/evalcast-plot")
```

**Comment by zterner-mitre** [comment]
The first `plot_calibration` is giving this warning and this plot, which I think is probably not what you are aiming for?
image
image

The second `plot_calibration` seems good:
image

Third also seems good
image

**Comment by zterner-mitre** [comment]
`plot_coverage` and `plot_width` are producing too many plots given the setup of the plots (all in one row, for instance), and also may be missing some data. I can share those with you here, or open another issue, whichever you prefer

**Comment by dshemetov** [comment]
What does your `predictions_cards` look like? My first plot does not match yours.

**Comment by dshemetov** [comment]
I think the issue might be that your plots are using the full forecast_dates instead of the reduced forecast_dates_dec

**Comment by zterner-mitre** [comment]
Yep! That's it. I had manually defined `forecast_dates_dec` yesterday when I was having issues with `get_covidhub_forecast_dates` to be all dates within December. But using the sequence of 4 dates instead of 31 fixed everything. Thanks!

**Comment by dshemetov** [comment]
Excellent!

**Pull request merged**
