### PR TITLE
Fix hospitalization correlations that end in October

### PR DESCRIPTION
**Pull request by benjaminysmith**
Switch from smoothed_adj_covid19 to smoothed_adj_covid19_from_claims.

### CODE REVIEW

**Review by krivard — APPROVED** [review]
👍

**Comment by krivard** [comment]
(why is the evalcast build failing?)

**Comment by benjaminysmith** [comment]
Evalcast passed after updating the cache as @chinandrew suggested.

**Comment by krivard** [comment]
lol

**Pull request merged**
