### PR TITLE
Disable stringsAsFactors during unit testing

### PR DESCRIPTION
**Pull request by capnrefsmmat**
See comment. This meant the tests ran on R 4.0 (my machine) but not on 3.5 (CI), and I didn't notice because we need to land #289 to have `r-pkg-devel` be tested.

cc @chinandrew

### CODE REVIEW

**Comment by chinandrew** [comment]
Just for context, CI is 3.5 since the DESCRIPTION file in covidcast has `Depends: R (>= 3.5.0)`. We can easily add more versions or adjust versions if needed.

**Comment by capnrefsmmat** [comment]
Maybe we stick with 3.5 for now, and after we figure out why the dependency cache doesn't always work, we add 4.0 as well?

(Ubuntu 18.04 LTS is actually on 3.4, which we don't support. We probably don't want to bump the minimum past 3.5 for a while, since it's probably still in wide use on slightly newer distros.)

**Comment by chinandrew** [comment]
I'm going to merge my branch into this one so the CI runs with the changes.

**Comment by chinandrew** [comment]
Looks like we're good.

**Review by sgsmob — APPROVED** [review]

**Pull request merged**
