### PR TITLE
Add PR to fips<>name and territories to fips<>abbr/ fips<>name to R package

### LINKED ISSUE #446: covidcast::fips_to_name for Puerto Rico
The FIPS 72000 is recognized in `fips_to_abbr` but not in `fips_to_name`:

```
> covidcast::fips_to_abbr("72000")
72000 
 "PR" 
> covidcast::abbr_to_fips("PR")
     PR 
"72000" 
```

But then...
```
> covidcast::fips_to_name("72000")
72000 
   NA 
```

### PR DESCRIPTION
**Pull request by chinandrew**
Addresses #446 and #461  for R package

Since the PR and territories data comes from multiple xlsx files in different formats, as well as some web pages for name/fips mappings, I constructed individual rda files by hand for PR and territories that are stored in data-raw/ and joined with the data pulled from the census when Make.R is run. Similar pattern to how the geomapper in delphi_utils generates the mapping files.

```
> library(covidcast)
> covidcast::fips_to_name("72000")
        72000 
"Puerto Rico" 
> covidcast::fips_to_name("72001")
     72001 
"Adjuntas" 
> covidcast::name_to_fips("Puerto Rico")
Puerto Rico 
    "72000" 
> covidcast::fips_to_abbr("66")
66000 
 "GU" 
> covidcast::fips_to_abbr("78")
78000 
 "VI" 
> covidcast::abbr_to_fips("MP")
     MP 
"69000" 
> covidcast::abbr_to_fips("VI")
     VI 
"78000" 
```

Have not rebuilt documentation yet, if that should go in this PR let me know and I'll add.

### CODE REVIEW

**Comment by capnrefsmmat** [comment]
Hmm. So `county_census` is generated [here](https://github.com/cmu-delphi/covidcast/blob/main/R-packages/data-raw/make.R) if we ever need to build it from scratch. Should we add this in there? And then also build in the subsetting @statsmaths made in #493?

I kind of forgot we had the raw data generated like this, but I guess we should bring the generator up to date. @statsmaths, if you could help that'd be great.

**Review by sgsmob — APPROVED** [review]

**Comment by chinandrew** [comment]
> Hmm. So `county_census` is generated [here](https://github.com/cmu-delphi/covidcast/blob/main/R-packages/data-raw/make.R) if we ever need to build it from scratch. Should we add this in there? And then also build in the subsetting @statsmaths made in #493?
> 
> I kind of forgot we had the raw data generated like this, but I guess we should bring the generator up to date. @statsmaths, if you could help that'd be great.

Oh I wasn't aware of that. I had to pull 2 xlsx files, one for pop/name and one for name/fips, and join them to get the df, which I did by hand. I can write up a script to do it and add to that file if that's preferred. 

US territories is even more convoluted, I think each territory had its own xlsx file without fips and I pulled the name <> fips from wikipedia (since the names aren't always consistent and. [this .gov site](https://www.nrcs.usda.gov/wps/portal/nrcs/detail/national/home/?cid=nrcs143_013697) doesnt use the same county names as the census)

**Comment by capnrefsmmat** [comment]
Yeah, I think having it all in that file would be great, and we could then add some code comments so we remember that the data is generated by the file. It'd be great if the Census data we pulled could just be extended with a few territory entries, instead of needing to merge a bunch of different things.

**Comment by chinandrew** [comment]
Alternatively I could do what I did for the python geomapper and hard code the numbers into the data generation script: https://github.com/cmu-delphi/covidcast-indicators/pull/668/files

**Comment by chinandrew** [comment]
> And then also build in the subsetting @statsmaths made in #493?

Also what's the subsetting you're referring to here?

**Comment by capnrefsmmat** [comment]
> Alternatively I could do what I did for the python geomapper and hard code the numbers into the data generation script: https://github.com/cmu-delphi/covidcast-indicators/pull/668/files

I think that makes sense

> Also what's the subsetting you're referring to here?

Taylor subset the columns in `county_census` so it didn't have as many columns as the script generates, since most of them weren't needed

**Comment by chinandrew** [comment]
Ok updated this PR to include territories and add the code to Make.R. I put the hand-constructed territories data into rda files within the data-raw folder. 

Ready for another review @capnrefsmmat @sgsmob

**Review by sgsmob — APPROVED** [review]

**Comment by statsmaths** [comment]
This looks great. Once you merge, I will also add the code I have to create the smaller geojson files into the data-raw directory.

**Review by capnrefsmmat — APPROVED** [review]
looks good

**Pull request merged**
