### PR TITLE
Document a Git Flow release process

### PR DESCRIPTION
**Pull request by capnrefsmmat**
I propose we follow this process for future covidcast releases. This will require us to work on a branch until we're ready to release, but it affords us the opportunity to beta-test before release.

### CODE REVIEW

**Comment by chinandrew** [comment]
What are your thoughts on using this for the Python package too, even though the actual deploy process there is different and doesn't have the same complications? Main benefits in my mind are 1) consistency and 2) ability to checkout the pypi version easily (slightly quicker than finding the commit sha). I don't feel super strongly either way. Seems fairly unnecessary process wise, but consistency isn't worthless.

**Comment by capnrefsmmat** [comment]
I think the main benefit for the Python package would be the documentation -- the Sphinx site is deployed instantly when the HTML is pushed to `main`. We could also just be careful not to commit the HTML until we're ready to release. That's just waiting for a mistake to happen, though/

**Comment by capnrefsmmat** [comment]
@chinandrew Just realized this process will also require us to change the R CI workflow to trigger on PRs to `r-pkg-devel` as well as `main`.

**Comment by chinandrew** [comment]
>the Sphinx site is deployed instantly when the HTML is pushed to `main`

Did not realize that was the case, that seems to be a good reason to use this for Python too.

> @chinandrew Just realized this process will also require us to change the R CI workflow to trigger on PRs to `r-pkg-devel` as well as `main`.

Yup, that shouldn't be difficult to setup.

**Review by sgsmob — APPROVED** [review]

**Pull request merged**
