### PR TITLE
Support weekly time_type in python package

### PR DESCRIPTION
**Pull request by dshemetov**
This is the Python analogue of #380. Adds time_type support to `signal` and `_date_to_api_string` and modifies fetching logic slightly for both async and non-async calls.

A demo call to `nchs-mortality` with my local branch:
```

> remote_signal_name = "nchs-mortality"
> signal_type = "deaths_covid_incidence_num"
> geo_type = "state"
> start_day = date(2021, 1, 1)
> end_day = date(2021, 4, 20)
> df1 = covidcast.signal(remote_signal_name, signal_type, start_day, end_day, geo_type, time_type="week")
> df1 = df1.reset_index().set_index(["geo_value", "time_value"]).sort_index()
> print(df1.index.levels[1])
> print(df1["issue"].unique())
DatetimeIndex(['2020-12-27', '2021-01-03', '2021-01-10', '2021-01-17',
               '2021-01-24', '2021-01-31', '2021-02-07', '2021-02-14',
               '2021-02-21', '2021-02-28', '2021-03-07', '2021-03-14',
               '2021-03-21', '2021-03-28', '2021-04-04', '2021-04-11'],
              dtype='datetime64[ns]', name='time_value', freq=None)
['2021-04-18T00:00:00.000000000' '2021-04-11T00:00:00.000000000'
 '2021-01-24T00:00:00.000000000' '2021-01-31T00:00:00.000000000'
 '2021-02-14T00:00:00.000000000' '2021-02-21T00:00:00.000000000'
 '2021-02-28T00:00:00.000000000' '2021-03-07T00:00:00.000000000'
 '2021-03-14T00:00:00.000000000' '2021-03-21T00:00:00.000000000'
 '2021-03-28T00:00:00.000000000' '2021-04-04T00:00:00.000000000'
 '2021-01-03T00:00:00.000000000' '2021-01-10T00:00:00.000000000']

> remote_signal_name = "nchs-mortality"
> signal_type = "deaths_covid_incidence_num"
> geo_type = "state"
> start_day = date(2021, 1, 1)
> end_day = date(2021, 4, 20)
> issue = date(2021, 2, 14)
> df1 = covidcast.signal(remote_signal_name, signal_type, start_day, end_day, geo_type, time_type="week", issues=issue)
> df1 = df1.reset_index().set_index(["geo_value", "time_value"]).sort_index()
> df1["issue"].unique()
array(['2021-02-14T00:00:00.000000000'], dtype='datetime64[ns]')

> remote_signal_name = "nchs-mortality"
> signal_type = "deaths_covid_incidence_num"
> geo_type = "state"
> start_day = date(2021, 1, 1)
> end_day = date(2021, 4, 20)
> as_of = date(2021, 2, 14)
> df1 = covidcast.signal(remote_signal_name, signal_type, start_day, end_day, geo_type, time_type="week", as_of=as_of)
> df1 = df1.reset_index().set_index(["geo_value", "time_value"]).sort_index()
> df1["issue"].le(pd.to_datetime(as_of)).all()
True

### CODE REVIEW

**Comment by chinandrew** [comment]
What happens if you give it a date that isn't the first day of the week?

**Comment by dshemetov** [comment]
It converts it to the corresponding epiweek. Basically, the inputs to covidcast.signal are assumed to be regular date(Y, M, D) dates, which are converted to the corresponding epiweeks "YYYYMM" format as needed by Epidata.

**Comment by dshemetov** [comment]
In the example above, 8-1 was converted to 7-26

**Comment by chinandrew** [comment]
> In the example above, 8-1 was converted to 7-26. I could modify that so that we never grab epiweek dates earlier than start_day.

That seems fine, let's juts add a note in the documentation that it rounds dates to the epiweek.

**Comment by dshemetov** [comment]
Sounds good. I did a couple more sanity checks on real data calls and we're successfully pulling as_of dates and correct issues for nchs_mortality.

**Comment by dshemetov** [comment]
I messed this PR and branch up by playing with covidcast repo history and deleting the talks. Reopening a new PR.

**Pull request closed without merging**
