### PR TITLE
Add S3 class typing to cards

### PR DESCRIPTION
**Pull request by sgsmob**
Annotate an S3 class onto each tibble in the lists returned by `evalcast::get_covidhub_predictions()` and `evalcast::evaluate_predictions()` ("prediction_card" and "score_card", respectively). This will allow us to have generic methods for printing (#222) and aggregating (#221) the cards while allowing specialized behavior for the two types of cards.

See also #150.

### CODE REVIEW

**Review by dajmcdon — APPROVED** [review]

**Comment by dajmcdon** [comment]
Sorry, @sgsmob I approved this too quickly and had to revert. 

The "score_card" in `evaluate.R` is just one card, while the `prediction_cards` from covidhub may be 1 card, or more likely, many. 

Both aggregating and printing need to handle 1 or many. My instinct is that we should always expect "cards" and attach the class as plural to the list of lists rather than to each individual card. Your current version classes 1 card in `evaluate.R` and plural cards in `get_covidhub_predictions`.

Prediction cards (generally many) are also produced by `get_predictions()`, so we need the same result there.

**Comment by sgsmob** [comment]
I think we want the cards to be labeled; the divergent behavior between the aggregation functions is actually (here)[https://github.com/cmu-delphi/covidcast/blob/9c5848152b966fb97cff666059ee8574e07b16e9/R-packages/evalcast/R/plot_trajectory.R#L43] where we are iterating over the cards.

**Comment by dajmcdon** [comment]
My feeling is that the aggregation should begin on the line above your link (line 42). So we take in a list of cards, and implement the processing that goes from 43 to 58. Does that make sense? We want to turn all cards at once into one giant tibble.

**Comment by sgsmob** [comment]
It does make sense but we don't have to decide what type of card we are dealing with until we unpack the cards in L43.  So the workflow would look like:

```
unpack_single_card <- function(card) {
    UseMethod("unpack_single_card", card)
}

unpack_single_card.prediction_card <- function(card) {
     # ...
}

unpack_single_card.evaluation_card <- function(card) {
    # ...
}

aggregate_cards <- function(list_of_cards) {
    return list_of_cards %>% purrr::map_dfr(unpack_single_card)
}
```

**Comment by dajmcdon** [comment]
Ok. Works for me.

**Comment by sgsmob** [comment]
Logan's example in #223 does not work because the dimensions of the cards are not the same.  I never looked closer into that because I assumed I was doing something wrong since I didn't understand the output.  I will look into what assumptions the snippit from `plot_trajectory.R` was making and why it rejects dimension-mismatched cards.

**Comment by dajmcdon** [comment]
I think the trajectory plotting (and aggregation more generally) should accommodate the dimension mismatch. So we'll have to fix that up. This is a good example of the need to "fail gracefully" #224. Aggregating these shouldn't be an issue, nor should plotting.

**Pull request merged**
