### PR TITLE
3. Plotting documentation

### PR DESCRIPTION
**Pull request by chinandrew**
Summary of changes:
- Add documentation for the new plotting functionality.

This PR follows #34 and #27 (they should be merged first). Previously was #30 but git history got ugly on that due to files being added/deleted so just made a new branch with all the changes. Could have squashed and merged to main but didn't trust myself to remember that.

New rendered docs have not been committed yet. Waiting until we're ready for deploy.

### CODE REVIEW

**Comment by capnrefsmmat** [comment]
I'm suddenly getting this:

```
$ make html
Running Sphinx v3.1.1
loading pickled environment... done
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 1 source files that are out of date
updating environment: 0 added, 1 changed, 0 removed
reading sources... [100%] plot_examples                                                                                                    
/Users/alexreinhart/Research/COVIDcast/covidcast/Python-packages/covidcast-py/docs/plot_examples.rst:20: WARNING: Exception occurred in plotting plot_examples-1
 from /Users/alexreinhart/Research/COVIDcast/covidcast/Python-packages/covidcast-py/docs/plot_examples.rst:
Traceback (most recent call last):
  File "/Users/alexreinhart/miniconda3/lib/python3.6/site-packages/matplotlib/sphinxext/plot_directive.py", line 472, in run_code
    exec(code, ns)
  File "<string>", line 5, in <module>
  File "/Users/alexreinhart/Research/COVIDcast/covidcast/Python-packages/covidcast-py/covidcast/plotting.py", line 66, in plot_choropleth
    for shape in _project_and_transform(data_w_geo):
  File "/Users/alexreinhart/Research/COVIDcast/covidcast/Python-packages/covidcast-py/covidcast/plotting.py", line 141, in _project_and_transform
    cont = data.loc[[i not in ('02', '15', '72') for i in data.state_fips], :].to_crs(
  File "/Users/alexreinhart/miniconda3/lib/python3.6/site-packages/pandas/core/generic.py", line 5067, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'to_crs'
/Users/alexreinhart/Research/COVIDcast/covidcast/Python-packages/covidcast-py/docs/plot_examples.rst:35: WARNING: Exception occurred in plotting plot_examples-2
 from /Users/alexreinhart/Research/COVIDcast/covidcast/Python-packages/covidcast-py/docs/plot_examples.rst:
Traceback (most recent call last):
  File "/Users/alexreinhart/miniconda3/lib/python3.6/site-packages/matplotlib/sphinxext/plot_directive.py", line 472, in run_code
    exec(code, ns)
  File "<string>", line 5, in <module>
  File "/Users/alexreinhart/Research/COVIDcast/covidcast/Python-packages/covidcast-py/covidcast/plotting.py", line 66, in plot_choropleth
    for shape in _project_and_transform(data_w_geo):
  File "/Users/alexreinhart/Research/COVIDcast/covidcast/Python-packages/covidcast-py/covidcast/plotting.py", line 141, in _project_and_transform
    cont = data.loc[[i not in ('02', '15', '72') for i in data.state_fips], :].to_crs(
  File "/Users/alexreinhart/miniconda3/lib/python3.6/site-packages/pandas/core/generic.py", line 5067, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'to_crs'
/Users/alexreinhart/Research/COVIDcast/covidcast/Python-packages/covidcast-py/docs/plot_examples.rst:54: WARNING: Exception occurred in plotting plot_examples-3
 from /Users/alexreinhart/Research/COVIDcast/covidcast/Python-packages/covidcast-py/docs/plot_examples.rst:
Traceback (most recent call last):
  File "/Users/alexreinhart/miniconda3/lib/python3.6/site-packages/matplotlib/sphinxext/plot_directive.py", line 472, in run_code
    exec(code, ns)
  File "<string>", line 5, in <module>
  File "/Users/alexreinhart/Research/COVIDcast/covidcast/Python-packages/covidcast-py/covidcast/plotting.py", line 66, in plot_choropleth
    for shape in _project_and_transform(data_w_geo):
  File "/Users/alexreinhart/Research/COVIDcast/covidcast/Python-packages/covidcast-py/covidcast/plotting.py", line 141, in _project_and_transform
    cont = data.loc[[i not in ('02', '15', '72') for i in data.state_fips], :].to_crs(
  File "/Users/alexreinhart/miniconda3/lib/python3.6/site-packages/pandas/core/generic.py", line 5067, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'to_crs'
/Users/alexreinhart/Research/COVIDcast/covidcast/Python-packages/covidcast-py/docs/plot_examples.rst:134: WARNING: Exception occurred in plotting plot_examples-4
 from /Users/alexreinhart/Research/COVIDcast/covidcast/Python-packages/covidcast-py/docs/plot_examples.rst:
Traceback (most recent call last):
  File "/Users/alexreinhart/miniconda3/lib/python3.6/site-packages/matplotlib/sphinxext/plot_directive.py", line 472, in run_code
    exec(code, ns)
  File "<string>", line 7, in <module>
  File "/Users/alexreinhart/miniconda3/lib/python3.6/site-packages/pandas/core/generic.py", line 5067, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'to_crs'
```

It looks like `get_geo_df` is not returning a GeoDataFrame, just an ordinary one:

```
In [1]: import covidcast                                                                                                                   

In [2]: from datetime import date                                                                                                          

In [3]: foo = covidcast.signal("fb-survey", "raw_cli", date(2020, 8, 1), date(2020, 8, 1))                                                 

In [4]: type(covidcast.get_geo_df(foo))                                                                                                    
Out[4]: pandas.core.frame.DataFrame
```

**Comment by capnrefsmmat** [comment]
On the other hand, all tests pass! Probably should have a test that ensures `get_geo_df` returns a `GeoDataFrame` that can be used to do geographic things, though.

**Comment by chinandrew** [comment]
That's what I get for removing the test and also changing an interface at the same time, thanks. I think it's due to the fact that if you do `DF join GeoDF` you get a DF while `GeoDF join DF` you get a GeoDF. I've just cast it to a geoDF in the return and added tests for it.

**Comment by capnrefsmmat** [comment]
I pushed a couple small edits.

Question: When do you think we can safely release these features? There's an upcoming event next week (which I shouldn't post publicly here) that may get people using our package. I need to release a new version on PyPI, at the least so I have #36 in the release (so their API hits go to AWS). If I merge the PR, are you comfortable releasing the basic mapping features in 0.0.9 now?

**Pull request merged**
